[build]
target = "xtensa-esp32-espidf"

[unstable]
build-std = ["std", "panic_abort"]

[target.xtensa-esp32-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"

[env]
ESP_IDF_VERSION = "v5.3"
